server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # El backend acepta imagenes de 3 MB y el default de nginx corta en 1M
    client_max_body_size 5M;



    location / {
        try_files $uri $uri/ /index.html;
    }
}
